baseURL = 'https://www.aswf.io/openreviewinitiative/'
languageCode = 'en-us'
title = 'Open Review Initiative - ASWF'
theme = 'hugo-universal-theme'

# Site language
defaultContentLanguage = "en"

# Number of words of summarized post content
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]

[[menu.main]]
    name       = "ASWF"
    url        = "https://www.aswf.io"
    weight     = 1

[[menu.main]]
    name       = "Projects"
    url        = "https://www.aswf.io/projects"
    weight     = 2

[[menu.main]]
    name       = "Community"
    url        = "https://www.aswf.io/community"
    weight     = 3

[[menu.main]]
    name       = "GitHub"
    url        = "https://github.com/AcademySoftwareFoundation"
    weight     = 4

# Top bar social links menu
[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/AcademySoftwareFoundation"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/AcademySwF"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Academy Software Foundation"
    defaultKeywords = ["open review", "aswf", "academy software foundation", "post-production", "review"]
    mainSections = ["blog"]
    defaultDescription = "The Open Review Initiative by the Academy Software Foundation - Transforming post-production workflows through open source collaboration tools."

    # Social media
    facebook_site = ""
    twitter_site = "AcademySwF"
    default_sharing_image = "img/aswf-sharing.png"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Logo and branding
    disabled_logo = false
    logo_text = "Open Review Initiative"
    logo = "img/aswf_white.png"
    logo_small = "img/aswf_white.png"
    contact_url = "/contact"
    
    about_us = "<p>The Open Review Initiative by the Academy Software Foundation - Transforming post-production workflows through open source collaboration tools.</p>"
    copyright = "Copyright (c) 2023 Academy Software Foundation. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us at hello@aswf.io</p>
      <p class="hidden-md hidden-lg"><a href="mailto:hello@aswf.io" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 6

[params.video]
    enable = true
    title = "Walt Disney Animation Studios Sync Protocol Case Study"
    subtitle = "See the Open Review Initiative in action"
    video_url = "img/WDAS_Sync_Story.mp4"
    poster_url = "img/Walt-Disney-Animation-Studios.jpg"

[params.testimonials]
    enable = false
    title = "Testimonials"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Learn More About Our Projects"
    subtitle = "Explore our open source tools for post-production workflows"
    link_url = "https://github.com/AcademySoftwareFoundation"
    link_text = "View All Projects"

[params.clients]
    enable = false
    title = "Our Partners"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"